version: "3.8"
services:
  java-projects:
    build: .

  redis:
    build: ./domain-modules/secret-resources/dockerfiles/redis
    ports:
      - "6379:6379"
    networks:
      - myApp-network
    volumes:
      - myApp-redis-volume:/data
  mysql:
    build: ./domain-modules/secret-resources/dockerfiles/mysql
    ports:
      - "3306:3306"
    networks:
      - myApp-network
    volumes:
      - myApp-mysql-volume:/var/lib/mysql
networks:
  myApp-network:
    external: true
volumes:
  myApp-redis-volume:
    external: true
  myApp-mysql-volume:
    external: true
  myApp-volume:
    external: true
