FROM eclipse-temurin:17-jdk
WORKDIR /home/myApp/build

# 볼륨과 분리 (디렉토리 복사등 정상적인 행동이 될 수 없음)
COPY ./gradle/wrapper ./gradle/wrapper
COPY ./gradlew .
COPY ./gradlew.bat .
RUN chmod +x ./gradlew

ARG DISABLE_CACHE

COPY ./build.gradle .
COPY ./settings.gradle .
COPY ./api ./api
COPY ./domain-modules ./domain-modules

ENTRYPOINT ["./gradlew", ":api:bootRun", "--args=--spring.profiles.active=${ACTIVE_PROFILE} --app.mysql.server.url=${MYSQL_SERVER_URL} --app.redis.server.url=${REDIS_SERVER_URL} --app.kafka.server.url=${KAFKA_SERVER_URL}"]
#ENTRYPOINT ["./shell/api.sh"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]