version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8083:8083"
    networks:
      - myApp-network
    volumes:
      - myApp-volume:/app
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
  redis:
    build: ./domain-modules/secret-resources/dockerfiles/redis
    ports:
      - "6379:6379"
    networks:
      - myApp-network
    volumes:
      - myApp-volume:/redis/data
  mysql:
    build: ./domain-modules/secret-resources/dockerfiles/mysql
    ports:
      - "3306:3306"
    networks:
      - myApp-network
    volumes:
      - myApp-volume:/mysql/data
#  mail-server:
#    build: ./domain-modules/secret-resources/dockerfiles/mail_server
networks:
  myApp-network:
    external: true
volumes:
  myApp-volume:
    external: true
