FROM eclipse-temurin:17
WORKDIR /home/workdir/myApp

COPY ./gradle/wrapper ./gradle/wrapper
COPY ./gradlew.bat .
COPY ./gradlew .
RUN chmod +x ./gradlew

COPY ./settings.gradle .
COPY ./build.gradle .
COPY ./gateway ./gateway
COPY ./domain-modules ./domain-modules
ENTRYPOINT ["./gradlew",":gateway:bootRun", "--args=--spring.profiles.active=${ACTIVE_PROFILE} --app.mysql.server.url=${MYSQL_SERVER_URL} --app.redis.server.url=${REDIS_SERVER_URL} --app.kafka.server.url=${KAFKA_SERVER_URL}"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]