FROM gradle:jdk17

COPY build.gradle ./
COPY settings.gradle ./

COPY dispersion-queue ./dispersion-queue
COPY domain-modules ./domain-modules
COPY security ./security

RUN ["gradle", ":api:build","-PskipDownload=true", "-Dspring.profiles.active=dev'" ]

COPY --from=builder ./api/build/libs/*.jar ./api.jar

ENTRYPOINT ["java", "-jar", "api.jar"]