FROM eclipse-temurin:17-jdk
WORKDIR /home/myApp/build

ARG ACTIVE_PROFILE
ENV ACTIVE_PROFILE=${ACTIVE_PROFILE}
# 볼륨과 분리 (디렉토리 복사등 정상적인 행동이 될 수 없음)
COPY ./api ./api
COPY ./domain-modules ./domain-modules
COPY ./gradle/wrapper ./gradle/wrapper
COPY ./build.gradle .
COPY ./settings.gradle .
COPY ./gradlew .
COPY ./gradlew.bat .

ENTRYPOINT ["./gradlew",":api:bootRun", "--args='--spring.profiles.active=${ACTIVE_PROFILE}'"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]