FROM gradle:jdk17
WORKDIR /home/workdir/myApp

ARG ACTIVE_PROFILE
ENV ACTIVE_PROFILE=${ACTIVE_PROFILE}

COPY ./gateway ./gateway
COPY ./domain-modules ./domain-modules
COPY ./gradle/wrapper ./gradle/wrapper
COPY ./build.gradle .
COPY ./settings.gradle .
COPY ./gradlew .
COPY ./gradlew.bat .

ENTRYPOINT ["gradle",":gateway:bootRun", "--args='--spring.profiles.active=${ACTIVE_PROFILE}'"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]