#ldap.url=ldap://localhost:8389/dc=springframework,dc=org

#spring.ldap.urls=ldap://localhost:8389
#spring.ldap.base=dc=application,dc=my

#spring.ldap.embedded.ldif=classpath:server.ldif
#spring.ldap.embedded.base-dn=dc=springframework,dc=org
#spring.ldap.embedded.port=8389
spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true