#!/bin/sh
echo "push start"
chmod +x ./gradlew

# 푸시하려는 변경된 파일 목록 확인
CHANGED_FILES=$(git diff --cached --name-only HEAD)
echo "$CHANGED_FILES" | grep -q "^api/"
HAS_API_PATH=$?

echo "$CHANGED_FILES" | grep -q "^gateway/"
HAS_GATEWAY_PATH=$?

if [ $HAS_API_PATH ]; then
  docker-compose -f docker-compose-local.yml build api
  docker-compose --e push=true run myApp_api
  # 빌드 실패 시 푸시 중단
  if [ $? -ne 0 ]; then
      echo "Build failed. Push aborted."
      exit 1
  fi
fi


echo "build success!"