@startuml
entity Company {
    - id : Long
    - name : String
    - simpleExp : String
    - holidayWork : boolean
    - taxId : String
    - businessWeekTimeTable : BusinessWeekTimeTable
    - exceptionDayOffTimeTable : ExceptionDayOffTimeTable
    - exceptionBusinessTimeTable : ExceptionBusinessTimeTable
}

entity BusinessWeekTimeTable {
    - id : Long
    - company : Company
    - dayOfTheWeek : int
    - openTime : Time
    - closeTime : Time
    - startBreakTime : Time
    - endBreakTime : Time
}

entity ExceptionDayOffTimeTable {
        - id : Long
        - time : LocalDateTime
        - company : Company
        - reason : String
}

entity ExceptionBusinessTimeTable {
        - id : Long
        - time : LocalDateTime
        - company : Company
        - reason : String
}

entity CompanyReservationService {
    - id : Long
    - companyId : Long
    - companyInfo : Company
    - mainServices : List<CompanyReservationMainService>
}
note top of CompanyReservationService
    id : 업체 예약 시스템 id값
    companyId : 업체 id
    mainService : 예약 상세 서비스 클래스 리스트
end note

entity CompanyReservationMainService {
    - id : Long
    - revCompanyId : Long
    - content : String
    - timeTable : EachServiceTimeTable
    - term : Integer
    - ServiceDayOfTheWeek : String
    - staff : List<StaffMainService>
}
entity EachServiceTimeTable {
    - id : Long
    - service : CompanyReservationMainService
    - dayOfTheWeek : int
    - startBreakTime : Time
    - endBreakTime : Time
    - sameBusinessTime : Boolean
    - exceptionOpenTime : Time
    - exceptionCloseTime : Time
}
note left of CompanyReservationMainService::revCompanyId
    reservationCompany 외래키
end note
note left of CompanyReservationMainService::content
    서비스 내용
end note
note left of CompanyReservationMainService::openTime
    서비스 시작 시간
end note
note left of CompanyReservationMainService::closeTime
    서비스 종료 시간
end note
note left of CompanyReservationMainService::term
    서비스 간격
end note

entity Staff {
    - id : Long
    - companyId : Long
    - name : String
    - rank : String
    - introduce : String
}

entity StaffServiceInfo {
    - id : Long
    - staff : Staff
    - companyMainService : CompanyReservationMainService
    - price : int
    - staffExplain : String

}

entity ClientClientReservation {
    - id : Long
    - clientIdId : Client
    - clientReservationId : ClientReservation
}
note right of ClientClientReservation
 클라이언트와 클라이언트의 주문을
 연결만 해주는 테이블
 하나의 클라이언트는 여러 ClientClientReservation을
 가질 수 있다.
end note

entity ClientReservation {
    - id : Long
    - serviceDate : LocalDate
    - serviceTime : Time
    - message : String
    - staff : Staff
}

ClientClientReservation "1..*" -- "1" ClientReservation
Staff "1" -- "0..*" ClientReservation
Staff "1" -- "1..*" StaffServiceInfo

Company "1" -- "0..*" BusinessWeekTimeTable
Company "1" -- "0..*" ExceptionDayOffTimeTable
Company "1" -- "0..*" ExceptionBusinessTimeTable
Company "1" -- "0..*" CompanyReservationService
Company "1" -- "1..*" Staff
CompanyReservationService "1" -- "0..*" CompanyReservationMainService
CompanyReservationMainService "1" - "1..*" Staff
CompanyReservationMainService "1" -- "1..*" EachServiceTimeTable


@enduml