@startuml

entity DefaultBusinessTimeInfo {
    - id : Long
    - time : LocalDate
    - holiday : boolean
    - bizHoliday : boolean
    - company : Company
}

entity ExceptionDayOffTimeTable {
        - id : Long
        - time : LocalDateTime
        - company : Company
}

entity ExceptionBusinessTimeTable {
        - id : Long
        - time : LocalDateTime
        - company : Company
}

entity ReservationTime {
    - id : Long
    - clientId : Long
    - MainServiceId : Long
    - StaffId : Long
}

@enduml