@startuml

entity TimeTable {
    - id : Long
    - time : LocalDateTime
    - isHoliday : boolean
    - is
}

entity ReservationTime {
    - id : Long
    - clientId : Long
    - MainServiceId : Long
    - StaffId : Long
}

@enduml